Update mysql start and stop scripts
Use mysqladmin ping to determine when the daemon is running or not.
Hopefully a better way than using sleeps.

diff --git a/scripts/mysql/dbt3-mysql-start-db b/scripts/mysql/dbt3-mysql-start-db
--- a/scripts/mysql/dbt3-mysql-start-db
+++ b/scripts/mysql/dbt3-mysql-start-db
@@ -32,6 +32,9 @@ while getopts "fo:p:s:" OPT; do
 		DEFAULTS_FILE=${OPTARG}
 		DEFAULTS_FILE_ARG="--defaults-file=${DEFAULTS_FILE}"
 		;;
+	\0)
+		exit 1
+		;;
 	esac
 done
 
@@ -41,4 +44,18 @@ if [ -f "$PIDFILE" ]; then
 fi
 nohup mysqld_safe ${DEFAULTS_FILE_ARG} --datadir=$MYDATA \
 		--log-error=${OUTDIR}/${LOGFILE} > /dev/null 2>&1 &
-sleep 10
+
+count=0
+while [ 1 ]; do
+	mysqladmin -s ping > /dev/null
+	if [ $? -eq 1 ]; then
+		if [ $count -eq 60 ]; then
+			echo "failed waiting for mysql to start"
+			exit 1
+		fi
+		sleep 1
+		count=$(( $count + 1 ))
+		continue
+	fi
+	break
+done
diff --git a/scripts/mysql/dbt3-mysql-stop-db b/scripts/mysql/dbt3-mysql-stop-db
--- a/scripts/mysql/dbt3-mysql-stop-db
+++ b/scripts/mysql/dbt3-mysql-stop-db
@@ -16,14 +16,18 @@ fi
 HOSTNAME=`hostname`
 PIDFILE=$MYDATA/$HOSTNAME.pid
 
-if [ ! -f "$PIDFILE" ]; then
-	echo "MySQL pid file '$PIDFILE' does not exist."
-	echo "MySQL was not stopped, if it was running."
-	exit 0
-fi
-read MYSQL_PID < $PIDFILE
-kill ${MYSQL_PID} || exit 1
-sleep 10
-echo "MySQL stopped successfully (by kill)."
-
-exit 0
+mysqladmin -u root shutdown
+count=0
+while [ 1 ]; do
+	mysqladmin -s ping
+	if [ $? -ne 1 ]; then
+		if [ $count -eq 60 ]; then
+			echo "failed waiting for mysql to stop"
+			exit 1
+		fi
+		sleep 1
+		count=$(( $count + 1 ))
+		continue
+	fi
+	break
+done
