mysql-create-db: refactor usage and command line argument handling

diff --git a/scripts/mysql/dbt3-mysql-create-db.in b/scripts/mysql/dbt3-mysql-create-db.in
--- a/scripts/mysql/dbt3-mysql-create-db.in
+++ b/scripts/mysql/dbt3-mysql-create-db.in
@@ -19,21 +19,70 @@ if [ -z ${MYDATA} ]; then
     exit 1
 fi
 
-if [ -z ${DBNAME} ]; then
-    echo "DBNAME not defined."
-    exit 1
-fi
-
+DBNAME="dbt3"
 OUTPUT_DIR="."
-while getopts "o:p:" OPT; do
-	case ${OPT} in
-	o)
-		OUTPUT_DIR=${OPTARG}
+PRIVILEGED=0
+
+usage()
+{
+	cat << EOF
+$(basename "${0}") is the Database Test 3 (DBT-3) MySQL database creator
+
+Usage:
+  $(basename "${0}") [OPTION]
+
+Options:
+  --db-name      databse name
+  -o DIRECTORY   DIRECTORY to store test results
+  --privileged   stop and start database
+  -p             database parameters to use
+  -V, --version  output version information, then exit
+  -x DIRECTORY   set WAL to DIRECTORY
+  -?, --help     show this help, then exit
+
+@HOMEPAGE@
+EOF
+}
+
+# Custom argument handling for hopefully most portability.
+while [ "${#}" -gt 0 ] ; do
+	case "${1}" in
+	(--db-name)
+		shift
+		DBNAME="${1}"
 		;;
-	p)
-		PARAMETERS=${OPTARG}
+	(--db-name=?*)
+		DBNAME="${1#*--db-name=}"
+		;;
+	(-o)
+		shift
+		OUTPUT_DIR="${1}"
+		mkdir -p "${OUTPUT_DIR}"
+		;;
+	(--privileged)
+		PRIVILEGED=1
+		;;
+	(-p)
+		shift
+		# Intentionally do nothing at this time.
+		;;
+	(-V | --version)
+		echo "$(basename "${0}") (Database Test 3) v@PROJECT_VERSION@"
+		;;
+	(-\? | --help)
+		usage
+		exit 0
+		;;
+	(--* | -*)
+		echo "$(basename "${0}"): invalid option -- '${1}'"
+		echo "try \"$(basename "${0}") --help\" for more information."
+		exit 1
+		;;
+	(*)
+		break
 		;;
 	esac
+	shift
 done
 
 dbt3-mysql-stop-db
