mysql-drop-tables: refactor usage and command line argument handling

diff --git a/scripts/mysql/dbt3-mysql-drop-tables.in b/scripts/mysql/dbt3-mysql-drop-tables.in
--- a/scripts/mysql/dbt3-mysql-drop-tables.in
+++ b/scripts/mysql/dbt3-mysql-drop-tables.in
@@ -6,6 +6,54 @@
 #
 # Copyright The DBT-3 Authors
 
+usage()
+{
+	cat << EOF
+$(basename "${0}") is the Database Test 3 (DBT-3) MySQL table dropper
+
+Usage:
+  $(basename "${0}") [OPTION]
+
+Options:
+  --db-name      databse name, default $DBNAME
+  -V, --version  output version information, then exit
+  -?, --help     show this help, then exit
+
+@HOMEPAGE@
+EOF
+}
+
+DBNAME="dbt3"
+
+# Custom argument handling for hopefully most portability.
+while [ "${#}" -gt 0 ] ; do
+	case "${1}" in
+	(--db-name)
+		shift
+		DBNAME="${1}"
+		;;
+	(--db-name=?*)
+		DBNAME="${1#*--db-name=}"
+		;;
+	(-V | --version)
+		echo "$(basename "${0}") (Database Test 3) v@PROJECT_VERSION@"
+		;;
+	(-\? | --help)
+		usage
+		exit 0
+		;;
+	(--* | -*)
+		echo "$(basename "${0}"): invalid option -- '${1}'"
+		echo "try \"$(basename "${0}") --help\" for more information."
+		exit 1
+		;;
+	(*)
+		break
+		;;
+	esac
+	shift
+done
+
 MYSQL="mysql -u root -D $DBNAME"
 
 $MYSQL -e "DROP TABLE IF EXISTS supplier;"
