pgsql update usage and command line parsing
Make usage messages and command line argument handling more consistent.

diff --git a/scripts/pgsql/dbt3-pgsql-create-tables.in b/scripts/pgsql/dbt3-pgsql-create-tables.in
--- a/scripts/pgsql/dbt3-pgsql-create-tables.in
+++ b/scripts/pgsql/dbt3-pgsql-create-tables.in
@@ -6,6 +6,23 @@
 #
 # Copyright The DBT-3 Authors
 
+usage()
+{
+	cat << EOF
+$(basename "${0}") is the Database Test 3 (DBT-3) PostgreSQL table creator
+
+Usage:
+  $(basename "${0}") [OPTION]
+
+Options:
+  -t             usage tablespaces
+  -V, --version  output version information, then exit
+  -?, --help     show this help, then exit
+
+@HOMEPAGE@
+EOF
+}
+
 create_table() {
 	SQL=${1}
 
@@ -17,12 +34,29 @@ __EOF__
 
 NUM_OR_FD="NUMERIC"
 USE_TABLESPACES=0
-while getopts "t" OPT; do
-	case ${OPT} in
-	t)
+# Custom argument handling for hopefully most portability.
+while [ "${#}" -gt 0 ] ; do
+	case "${1}" in
+	(-t)
 		USE_TABLESPACES=1
 		;;
+	(-V | --version)
+		echo "$(basename "${0}") (Database Test 3) v@PROJECT_VERSION@"
+		;;
+	(-\? | --help)
+		usage
+		exit 0
+		;;
+	(--* | -*)
+		echo "$(basename "${0}"): invalid option -- '${1}'"
+		echo "try \"$(basename "${0}") --help\" for more information."
+		exit 1
+		;;
+	(*)
+		break
+		;;
 	esac
+	shift
 done
 
 PSQL="psql -v ON_ERROR_STOP=1 -X -A -t"
diff --git a/scripts/pgsql/dbt3-pgsql-drop-db.in b/scripts/pgsql/dbt3-pgsql-drop-db.in
--- a/scripts/pgsql/dbt3-pgsql-drop-db.in
+++ b/scripts/pgsql/dbt3-pgsql-drop-db.in
@@ -6,6 +6,23 @@
 #
 # Copyright The DBT-3 Authors
 
+usage()
+{
+	cat << EOF
+$(basename "${0}") is the Database Test 3 (DBT-3) PostgreSQL database dropper
+
+Usage:
+  $(basename "${0}") [OPTION]
+
+Options:
+  -l PORT        PostgreSQL listener PORT
+  -V, --version  output version information, then exit
+  -?, --help     show this help, then exit
+
+@HOMEPAGE@
+EOF
+}
+
 DIR=`dirname $0`
 . ${DIR}/pgsql_profile || exit 1
 
@@ -20,12 +37,30 @@ if [ -z ${PGDATABASE} ]; then
 	exit 1
 fi
 
-while getopts "l:" OPT; do
-	case ${OPT} in
-	l)
-		PORT=${OPTARG}
+# Custom argument handling for hopefully most portability.
+while [ "${#}" -gt 0 ] ; do
+	case "${1}" in
+	(-l)
+		shift
+		PORT="${1}"
+		;;
+	(-V | --version)
+		echo "$(basename "${0}") (Database Test 3) v@PROJECT_VERSION@"
+		;;
+	(-\? | --help)
+		usage
+		exit 0
+		;;
+	(--* | -*)
+		echo "$(basename "${0}"): invalid option -- '${1}'"
+		echo "try \"$(basename "${0}") --help\" for more information."
+		exit 1
+		;;
+	(*)
+		break
 		;;
 	esac
+	shift
 done
 
 if [ ! "x${PORT}" = "x" ]; then
diff --git a/scripts/pgsql/dbt3-pgsql-get-query-time.in b/scripts/pgsql/dbt3-pgsql-get-query-time.in
--- a/scripts/pgsql/dbt3-pgsql-get-query-time.in
+++ b/scripts/pgsql/dbt3-pgsql-get-query-time.in
@@ -6,18 +6,53 @@
 #
 # Copyright The DBT-3 Authors
 
+usage()
+{
+	cat << EOF
+$(basename "${0}") is the Database Test 3 (DBT-3) PostgreSQL query time extractor
+
+Usage:
+  $(basename "${0}") [OPTION]
+
+Options:
+  -o DIRECTORY   path to store query data
+  -V, --version  output version information, then exit
+  -?, --help     show this help, then exit
+
+@HOMEPAGE@
+EOF
+}
+
 SQL="SELECT task_name, s_time, e_time, (e_time-s_time) AS diff_time, \
 (extract(hour FROM (e_time-s_time)) * 3600) + (extract(minute FROM \
 (e_time-s_time)) * 60) + (extract(second FROM (e_time-s_time))) AS seconds \
 FROM time_statistics"
 
 ARGS=
-while getopts "o:" opt; do
-	case $opt in
-		o)
-			ARGS="-o $OPTARG/q_time.csv"
-			;;
+# Custom argument handling for hopefully most portability.
+while [ "${#}" -gt 0 ] ; do
+	case "${1}" in
+	(-o)
+		shift
+		ARGS="-o ${1}/q_time.csv"
+		;;
+	(-V | --version)
+		echo "$(basename "${0}") (Database Test 3) v@PROJECT_VERSION@"
+		;;
+	(-\? | --help)
+		usage
+		exit 0
+		;;
+	(--* | -*)
+		echo "$(basename "${0}"): invalid option -- '${1}'"
+		echo "try \"$(basename "${0}") --help\" for more information."
+		exit 1
+		;;
+	(*)
+		break
+		;;
 	esac
+	shift
 done
 
 psql -X -A -F, -t -q ${ARGS} -c "COPY (${SQL}) TO STDOUT (FORMAT CSV, HEADER)"
diff --git a/scripts/pgsql/dbt3-pgsql-get-version.in b/scripts/pgsql/dbt3-pgsql-get-version.in
--- a/scripts/pgsql/dbt3-pgsql-get-version.in
+++ b/scripts/pgsql/dbt3-pgsql-get-version.in
@@ -1,3 +1,42 @@
 #!/bin/sh
 @SHELLOPTIONS@
+
+usage()
+{
+	cat << EOF
+$(basename "${0}") is the Database Test 3 (DBT-3) PostgreSQL version reporter
+
+Usage:
+  $(basename "${0}") [OPTION]
+
+Options:
+  -V, --version  output version information, then exit
+  -?, --help     show this help, then exit
+
+@HOMEPAGE@
+EOF
+}
+
+# Custom argument handling for hopefully most portability.
+while [ "${#}" -gt 0 ] ; do
+	case "${1}" in
+	(-V | --version)
+		echo "$(basename "${0}") (Database Test 3) v@PROJECT_VERSION@"
+		;;
+	(-\? | --help)
+		usage
+		exit 0
+		;;
+	(--* | -*)
+		echo "$(basename "${0}"): invalid option -- '${1}'"
+		echo "try \"$(basename "${0}") --help\" for more information."
+		exit 1
+		;;
+	(*)
+		break
+		;;
+	esac
+	shift
+done
+
 pg_config --version
diff --git a/scripts/pgsql/dbt3-pgsql-load-data.in b/scripts/pgsql/dbt3-pgsql-load-data.in
--- a/scripts/pgsql/dbt3-pgsql-load-data.in
+++ b/scripts/pgsql/dbt3-pgsql-load-data.in
@@ -6,6 +6,25 @@
 #
 # Copyright The DBT-3 Authors
 
+usage()
+{
+	cat << EOF
+$(basename "${0}") is the Database Test 3 (DBT-3) PostgreSQL data loader
+
+Usage:
+  $(basename "${0}") [OPTION]
+
+Options:
+  -C PARTITIONS  how many PARTITIONS to break data into
+  -d             load data directory
+  -U             run test as an unprivileged user
+  -V, --version  output version information, then exit
+  -?, --help     show this help, then exit
+
+@HOMEPAGE@
+EOF
+}
+
 load_table()
 {
 	table=${1}
@@ -333,22 +352,36 @@ ALTER TABLE region ADD CONSTRAINT pk_region PRIMARY KEY USING INDEX pk_region;"
 DIRECT_LOAD=0
 NODES=0
 PRIVILEGED=1
-USE_TABLESPACES=0
-while getopts "C:dtU" OPT; do
-	case ${OPT} in
-	C)
-		CHUNKS=$OPTARG
+# Custom argument handling for hopefully most portability.
+while [ "${#}" -gt 0 ] ; do
+	case "${1}" in
+	(-C)
+		shift
+		CHUNKS="${1}"
 		;;
-	d)
+	(-d)
 		DIRECT_LOAD=1
 		;;
-	t)
-		USE_TABLESPACES=1
-		;;
-	U)
+	(-U)
 		PRIVILEGED=0
 		;;
+	(-V | --version)
+		echo "$(basename "${0}") (Database Test 3) v@PROJECT_VERSION@"
+		;;
+	(-\? | --help)
+		usage
+		exit 0
+		;;
+	(--* | -*)
+		echo "$(basename "${0}"): invalid option -- '${1}'"
+		echo "try \"$(basename "${0}") --help\" for more information."
+		exit 1
+		;;
+	(*)
+		break
+		;;
 	esac
+	shift
 done
 
 # Automatically parallelize to the number of available processors if not
diff --git a/scripts/pgsql/dbt3-pgsql-plan-disaster.in b/scripts/pgsql/dbt3-pgsql-plan-disaster.in
--- a/scripts/pgsql/dbt3-pgsql-plan-disaster.in
+++ b/scripts/pgsql/dbt3-pgsql-plan-disaster.in
@@ -1,6 +1,41 @@
 #!/bin/bash
 @SHELLOPTIONS@
 
+usage()
+{
+	cat << EOF
+$(basename "${0}") is the Database Test 3 (DBT-3) PostgreSQL plan disaster reporter
+
+Usage:
+  $(basename "${0}") [OPTION]
+  $(basename "${0}") FILENAME
+
+@HOMEPAGE@
+EOF
+}
+
+# Custom argument handling for hopefully most portability.
+while [ "${#}" -gt 0 ] ; do
+	case "${1}" in
+	(-V | --version)
+		echo "$(basename "${0}") (Database Test 3) v@PROJECT_VERSION@"
+		;;
+	(-\? | --help)
+		usage
+		exit 0
+		;;
+	(--* | -*)
+		echo "$(basename "${0}"): invalid option -- '${1}'"
+		echo "try \"$(basename "${0}") --help\" for more information."
+		exit 1
+		;;
+	(*)
+		break
+		;;
+	esac
+	shift
+done
+
 FILENAME=$1
 
 Q=`basename $FILENAME | cut -d "." -f 1`
