Fix typo in some error messages

diff --git a/scripts/dbt3-build-dbgen.in b/scripts/dbt3-build-dbgen.in
--- a/scripts/dbt3-build-dbgen.in
+++ b/scripts/dbt3-build-dbgen.in
@@ -37,9 +37,8 @@ EOF
 }
 
 errormsg() {
-	printf "ERROR: %s, try \"%s\" " "${1}" "$(basename "${0}")"
+	printf "ERROR: %s, try \"%s --help\" " "${1}" "$(basename "${0}")"
 	echo "for more information."
-	exit 1
 }
 
 # Custom argument handling for hopefully most portability.
@@ -80,12 +79,14 @@ done
 
 if [ $# -eq 0 ]; then
 	errormsg "missing DBMS command line parameter"
+	exit 1
 fi
 DBMS=${1}
 shift
 
 if [ $# -eq 0 ]; then
 	errormsg "missing DIRECTORY command line parameter"
+	exit 1
 fi
 DBGENDIR="$(realpath "${1}")"
 shift
@@ -101,6 +102,7 @@ fi
 SERIESFILE="${PATCHDIR}/series"
 if [ ! -f "${SERIESFILE}" ]; then
 	errormsg "missing 'series' file in '${PATCHDIR}'"
+	exit 1
 fi
 
 find "${QUERYDIR}" -mindepth 1 -maxdepth 1 -type d | \
