Make usage and command line handling consistent in top level script

diff --git a/scripts/dbt3-generate-report.in b/scripts/dbt3-generate-report.in
--- a/scripts/dbt3-generate-report.in
+++ b/scripts/dbt3-generate-report.in
@@ -6,13 +6,22 @@
 #
 # Copyright The DBT-3 Authors
 
-usage() {
-	echo "usage: $(basename $0) is the DBT-2 report generator"
-	echo ""
-	echo "usage: $(basename $0) [OPTIONS]"
-	echo ""
-	echo "General Options:"
-	echo "  -i <path>    DBT-3 results directory"
+usage()
+{
+	cat << EOF
+$(basename "${0}") is the Database Test 3 (DBT-3) report generator
+
+Usage:
+  $(basename "${0}") [OPTION]
+
+Options:
+  --fast         do not generate charts
+  -i DIRECTORY   DBT-3 results directory
+  -V, --version  output version information, then exit
+  -?, --help     show this help, then exit
+
+@HOMEPAGE@
+EOF
 }
 
 create_stat_page()
@@ -79,12 +88,33 @@ warning() {
 
 # Use this to skip chart generation to help test just the HTML generation.
 FAST=0
-while getopts fi: OPT; do
-	case $OPT in
-		f) export FAST=1;;
-		i) INDIR=$OPTARG;;
-		\?) usage; exit 1;;
+# Custom argument handling for hopefully most portability.
+while [ "${#}" -gt 0 ] ; do
+	case "${1}" in
+	(--fast)
+		export FAST=1
+		;;
+	(-i)
+		shift
+		INDIR="${1}"
+		;;
+	(-V | --version)
+		echo "$(basename "${0}") (Database Test 3) v@PROJECT_VERSION@"
+		;;
+	(-\? | --help)
+		usage
+		exit 0
+		;;
+	(--* | -*)
+		echo "$(basename "${0}"): invalid option -- '${1}'"
+		echo "try \"$(basename "${0}") --help\" for more information."
+		exit 1
+		;;
+	(*)
+		break
+		;;
 	esac
+	shift
 done
 
 if [ "x${INDIR}" = "x" ]; then
diff --git a/scripts/dbt3-get-config.in b/scripts/dbt3-get-config.in
--- a/scripts/dbt3-get-config.in
+++ b/scripts/dbt3-get-config.in
@@ -6,10 +6,44 @@
 #
 # Copyright The DBT-3 Authors
 
-if [ $# -lt 5 ]; then
-        echo "usage: $0 <scale_factor> <number of stream> <load parameters> <load parameters> <throughput parameters> <output_dir>"
-        exit 1
-fi
+usage()
+{
+	cat << EOF
+$(basename "${0}") is the Database Test 3 (DBT-3) system cofiguration collector
+
+Usage:
+  $(basename "${0}") [OPTION]
+  $(basename "${0}") SCALE_FACTOR STREAMS LOAD_PARMETERS POWER_PARAMETERS THROUGHPUT_PARAMETERS DIRECTORY
+
+Options:
+  -V, --version  output version information, then exit
+  -?, --help     show this help, then exit
+
+@HOMEPAGE@
+EOF
+}
+
+# Custom argument handling for hopefully most portability.
+while [ "${#}" -gt 0 ] ; do
+	case "${1}" in
+	(-V | --version)
+		echo "$(basename "${0}") (Database Test 3) v@PROJECT_VERSION@"
+		;;
+	(-\? | --help)
+		usage
+		exit 0
+		;;
+	(--* | -*)
+		echo "$(basename "${0}"): invalid option -- '${1}'"
+		echo "try \"$(basename "${0}") --help\" for more information."
+		exit 1
+		;;
+	(*)
+		break
+		;;
+	esac
+	shift
+done
 
 scale_factor=$1
 num_stream=$2
diff --git a/scripts/dbt3-throughput-score.in b/scripts/dbt3-throughput-score.in
--- a/scripts/dbt3-throughput-score.in
+++ b/scripts/dbt3-throughput-score.in
@@ -8,21 +8,56 @@
 
 usage()
 {
-	echo "usage: $0 -i <q_time.out> -n <streams> -s <scale factor>"
+	cat << EOF
+$(basename "${0}") is the Database Test 3 (DBT-3) throughput score calculator
+
+Usage:
+  $(basename "${0}") [OPTION]
+
+Options:
+  -i CSV         q_time.csv file
+  -n STREAMS     number of throughput STREAMS
+  -s SCALE_FACTOR
+                 SCALE_FACTOR of the test
+  -V, --version  output version information, then exit
+  -?, --help     show this help, then exit
+
+@HOMEPAGE@
+EOF
 }
 
-while getopts "i:n:s:" OPT; do
-	case ${OPT} in
-	i)
-		INFILE=${OPTARG}
+# Custom argument handling for hopefully most portability.
+while [ "${#}" -gt 0 ] ; do
+	case "${1}" in
+	(-i)
+		shift
+		INFILE="${1}"
 		;;
-	n)
-		STREAMS=${OPTARG}
+	(-n)
+		shift
+		STREAMS="${1}"
 		;;
-	s)
-		SCALE_FACTOR=${OPTARG}
+	(-s)
+		shift
+		SCALE_FACTOR="${1}"
+		;;
+	(-V | --version)
+		echo "$(basename "${0}") (Database Test 3) v@PROJECT_VERSION@"
+		;;
+	(-\? | --help)
+		usage
+		exit 0
+		;;
+	(--* | -*)
+		echo "$(basename "${0}"): invalid option -- '${1}'"
+		echo "try \"$(basename "${0}") --help\" for more information."
+		exit 1
+		;;
+	(*)
+		break
 		;;
 	esac
+	shift
 done
 
 if [ -z ${INFILE} ] || [ -z ${STREAMS} ] || [ -z ${SCALE_FACTOR} ]; then
diff --git a/scripts/dbt3-throughput-stream-wrapper.in b/scripts/dbt3-throughput-stream-wrapper.in
--- a/scripts/dbt3-throughput-stream-wrapper.in
+++ b/scripts/dbt3-throughput-stream-wrapper.in
@@ -6,28 +6,91 @@
 #
 # Copyright The DBT-3 Authors
 
+usage()
+{
+	cat << EOF
+$(basename "${0}") is the Database Test 3 (DBT-3) throughput stream wrapper
+
+Usage:
+  $(basename "${0}") [OPTION]
+
+Options:
+  -a DBMS        database management system to test
+  -f SCALE       database scale factor, default 1
+  -n STREAMS     number of throughput STREAMS
+  -o DIRECTORY   DIRECTORY to store test results
+  -s SEED        set SEED to a specific value
+  -U             run test as an unprivileged user
+  -Y             enable profiling (Linux only)
+  -V, --version  output version information, then exit
+  -z             do not run refresh streams
+  -?, --help     show this help, then exit
+
+DBMS options are:
+  monetdb    MonetDB
+  mysql      MySQL
+  pgsql      PostgreSQL
+  pgxl       Postgres-XL
+  virtuoso   Virtuoso
+
+PostgreSQL specific options:
+  -e             EXPLAIN ANALYZE
+
+@HOMEPAGE@
+EOF
+}
+
 NO_REFRESH=0
-while getopts "a:ef:n:o:s:Uz" opt; do
-	case $opt in
-	a) DATABASE=$OPTARG
+
+# Custom argument handling for hopefully most portability.
+while [ "${#}" -gt 0 ]; do
+	case "${1}" in
+	(-a)
+		shift
+		DATABASE="${1}"
 		;;
-	e) EXTRA_ARGS="$EXTRA_ARGS -e"
+	(-e)
+		EXTRA_ARGS="$EXTRA_ARGS -e"
 		;;
-	f) scale_factor=$OPTARG
+	(-f)
+		shift
+		scale_factor="${1}"
 		;;
-	n) num_stream=$OPTARG
+	(-n)
+		shift
+		num_stream="${1}"
 		;;
-	o) OUTPUT_DIR=$OPTARG
+	(-o)
+		shift
+		OUTPUT_DIR="${1}"
 		;;
-	s) SEED_FILE=$OPTARG
+	(-s)
+		shift
+		SEED_FILE="${1}"
 		;;
-	U) UNPRIVILEGED_ARG="-U"
+	(-U)
+		UNPRIVILEGED_ARG="-U"
 		;;
-	z) NO_REFRESH=1
+	(-V | --version)
+		echo "$(basename "${0}") (Database Test 3) v@PROJECT_VERSION@"
 		;;
-	\?) exit 1
+	(-z)
+		NO_REFRESH=1
+		;;
+	(-\? | --help)
+		usage
+		exit 0
+		;;
+	(--* | -*)
+		echo "$(basename "${0}"): invalid option -- '${1}'"
+		echo "try \"$(basename "${0}") --help\" for more information."
+		exit 1
+		;;
+	(*)
+		break
 		;;
 	esac
+	shift
 done
 
 if [ "x$DATABASE" = "x" ]; then
diff --git a/scripts/dbt3-throughput-stream.in b/scripts/dbt3-throughput-stream.in
--- a/scripts/dbt3-throughput-stream.in
+++ b/scripts/dbt3-throughput-stream.in
@@ -6,26 +6,86 @@
 #
 # Copyright The DBT-3 Authors
 
-MPP=0
+usage()
+{
+	cat << EOF
+$(basename "${0}") is the Database Test 3 (DBT-3) throughput test stream executor
 
-while getopts "a:ef:n:o:s:t:" opt; do
-	case $opt in
-	a) DATABASE=$OPTARG
-		if [ "x$DATABASE" = "xpgxl" ]; then
-			MPP=1
-		fi
+Usage:
+  $(basename "${0}") [OPTION]
+
+Options:
+  -a DBMS        database management system to test
+  -f SCALE       database scale factor, default 1
+  -n STREAMS     number of throughput STREAMS
+  -o DIRECTORY   DIRECTORY to store test results
+  -s SEED        set SEED to a specific value
+  -t STREAM      set STREAM identifier
+  -V, --version  output version information, then exit
+  -?, --help     show this help, then exit
+
+DBMS options are:
+  monetdb    MonetDB
+  mysql      MySQL
+  pgsql      PostgreSQL
+  pgxl       Postgres-XL
+  virtuoso   Virtuoso
+
+PostgreSQL specific options:
+  -e             EXPLAIN ANALYZE
+
+@HOMEPAGE@
+EOF
+}
+
+# Custom argument handling for hopefully most portability.
+while [ "${#}" -gt 0 ]; do
+	case "${1}" in
+	(-a)
+		shift
+		DATABASE="${1}"
 		;;
-	e) EXTRA_ARGS="-i \"${DSS_QUERY}/explain-analyze.sql\""
+	(-e)
+		EXTRA_ARGS="-i \"${DSS_QUERY}/explain-analyze.sql\""
 		;;
-	f) SCALE_FACTOR=$OPTARG;;
-	n) num_stream=$OPTARG;;
-	o) OUTPUT_DIR=$OPTARG
+	(-f)
+		shift
+		SCALE_FACTOR="${1}"
+		;;
+	(-n)
+		shift
+		num_stream="${1}"
+		;;
+	(-o)
+		shift
+		OUTPUT_DIR="${1}"
 		mkdir -p $OUTPUT_DIR/results
 		;;
-	s) SEED_FILE=$OPTARG;;
-	t) stream_num=$OPTARG;;
-	\?) exit 1;;
+	(-s)
+		shift
+		SEED_FILE="${1}"
+		;;
+	(-t)
+		shift
+		stream_num="${1}"
+		;;
+	(-V | --version)
+		echo "$(basename "${0}") (Database Test 3) v@PROJECT_VERSION@"
+		;;
+	(-\? | --help)
+		usage
+		exit 0
+		;;
+	(--* | -*)
+		echo "$(basename "${0}"): invalid option -- '${1}'"
+		echo "try \"$(basename "${0}") --help\" for more information."
+		exit 1
+		;;
+	(*)
+		break
+		;;
 	esac
+	shift
 done
 
 if [ "x$DATABASE" = "x" ]; then
diff --git a/scripts/dbt3-throughput-test.in b/scripts/dbt3-throughput-test.in
--- a/scripts/dbt3-throughput-test.in
+++ b/scripts/dbt3-throughput-test.in
@@ -7,43 +7,48 @@
 # Copyright The DBT-3 Authors
 
 MPP=0
-NO_REFRESH=0
 NO_REFRESH_FLAG=
 PRIVILEGED=1
+PROFILE=0
 EXTRA_ARGS=
 STATS=0
 
 usage()
 {
-	echo
-	echo "`basename $0` is the DBT-3 throughput runner"
-	echo ""
-	echo "Usage:"
-	echo "  `basename $0` [OPTIONS]"
-	echo
-	echo "Generate options:"
-	echo "  -a DBMS         database management system to test"
-	echo "  -f SCALE        database scale factor, default 1"
-	echo "  -h              this help message"
-	echo "  -n STREAMS      number of throughput streams"
-	echo "  -o DIRECTORY    path to store test results"
-	echo "  -s SEED         seed to use for power and throughput tests"
-	echo "  -S              enable system and database stats collection"
-	echo "  -u              use tablespaces"
-	echo "  -U              run test as an unprivileged user"
-	echo "  -Y              enable software profiling (Linux only)"
-	echo "  -z              do not run refresh streams"
-	echo ""
-	echo "DBMS options are:"
-	echo "  monetdb         MonetDB"
-	echo "  mysql           MySQL"
-	echo "  pgsql           PostgreSQL"
-	echo "  pgxl            Postgres-XL"
-	echo "  virtuoso        Virtuoso"
-	echo ""
-	echo "PostgreSQL specific options:"
-	echo "  -e              EXPLAIN ANALYZE"
-	echo "  -p              database parameters for the load test"
+	cat << EOF
+$(basename "${0}") is the Database Test 3 (DBT-3) throughput tester
+
+Usage:
+  $(basename "${0}") [OPTION]
+
+Options:
+  -a DBMS        database management system to test
+  -f SCALE       database scale factor, default 1
+  -n STREAMS     number of throughput STREAMS
+  -o DIRECTORY   DIRECTORY to store test results
+  -s SEED        set SEED to a specific value
+  -S             enable system and database stats collection"
+  -t STREAM      set STREAM identifier
+  -u             use tablespaces"
+  -U             run test as an unprivileged user"
+  -V, --version  output version information, then exit
+  -Y             enable software profiling (Linux only)"
+  -z             do not run refresh streams"
+  -?, --help     show this help, then exit
+
+DBMS options are:
+  monetdb    MonetDB
+  mysql      MySQL
+  pgsql      PostgreSQL
+  pgxl       Postgres-XL
+  virtuoso   Virtuoso
+
+PostgreSQL specific options:
+  -e             EXPLAIN ANALYZE
+  -p             database parameters for the throughput test"
+
+@HOMEPAGE@
+EOF
 }
 
 stop_procs() {
@@ -56,43 +61,70 @@ stop_procs() {
 }
 trap 'stop_procs' INT TERM
 
-while getopts "a:ef:hn:o:p:s:SUz" opt; do
-	case $opt in
-	a) DATABASE=$OPTARG
+# Custom argument handling for hopefully most portability.
+while [ "${#}" -gt 0 ]; do
+	case "${1}" in
+	(-a)
+		shift
+		DATABASE="${1}"
 		if [ "x$DATABASE" = "xpgxl" ]; then
 			MPP=1
 		fi
 		;;
-	e) EXTRA_ARGS="$EXTRA_ARGS -e"
+	(-e)
+		EXTRA_ARGS="$EXTRA_ARGS -e"
 		;;
-	f) scale_factor=$OPTARG
+	(-f)
+		shift
+		scale_factor="${1}"
 		;;
-	h) usage
-		exit 0
+	(-n)
+		shift
+		num_stream="${1}"
 		;;
-	n) num_stream=$OPTARG
-		;;
-	o) OUTPUT_DIR=$OPTARG
+	(-o)
+		shift
+		OUTPUT_DIR="${1}"
 		mkdir -p $OUTPUT_DIR/results
 		;;
-	p)
-		PARAMETERS_ARG="-p \"$OPTARG\""
+	(-p)
+		shift
+		PARAMETERS_ARG="-p \"${1}\""
 		;;
-	s) SEED_FILE=$OPTARG
+	(-s)
+		shift
+		SEED_FILE="${1}"
 		;;
-	S) STATS=1
+	(-S)
+		STATS=1
 		;;
-	U) PRIVILEGED=0
+	(-U)
+		PRIVILEGED=0
 		UNPRIVILEGED_ARG="-U"
 		;;
-	Y) PROFILE=1
+	(-Y)
+		PROFILE=1
 		;;
-	z) NO_REFRESH_FLAG="-z"
-		NO_REFRESH=1
+	(-V | --version)
+		echo "$(basename "${0}") (Database Test 3) v@PROJECT_VERSION@"
 		;;
-	\?) exit 1
+	(-z)
+		NO_REFRESH_FLAG="-z"
+		;;
+	(-\? | --help)
+		usage
+		exit 0
+		;;
+	(--* | -*)
+		echo "$(basename "${0}"): invalid option -- '${1}'"
+		echo "try \"$(basename "${0}") --help\" for more information."
+		exit 1
+		;;
+	(*)
+		break
 		;;
 	esac
+	shift
 done
 
 if [ "x$DATABASE" = "x" ]; then
