Use touchstone ts script
Hopefully easier overall this way to set up system and maintain scripts.

diff --git a/scripts/dbt3-load-test.in b/scripts/dbt3-load-test.in
--- a/scripts/dbt3-load-test.in
+++ b/scripts/dbt3-load-test.in
@@ -49,11 +49,11 @@ EOF
 }
 
 stop_procs() {
-	if which ts-sysstat > /dev/null 2>&1; then
-		ts-sysstat -o "${OUTPUT_DIR}/sysstat" -s &
+	if which ts > /dev/null 2>&1; then
+		ts sysstat -o "${OUTPUT_DIR}/sysstat" -s &
 	fi
-	if which "ts-${DATABASE}-stat" > /dev/null 2>&1; then
-		eval "ts-${DATABASE}-stat -o ${OUTPUT_DIR}/dbstat -s &"
+	if which ts > /dev/null 2>&1; then
+		eval "ts ${DATABASE}-stat -o ${OUTPUT_DIR}/dbstat -s &"
 	fi
 }
 trap 'stop_procs' INT TERM
@@ -247,10 +247,10 @@ fi
 
 if [ $STATS -eq 1 ]; then
 	# Start collecting system statistics.
-	if ! which ts-sysstat > /dev/null 2>&1; then
-		echo "WARNING: ts-sysstat not found for system stats collection"
+	if ! which ts > /dev/null 2>&1; then
+		echo "WARNING: ts not found for system stats collection"
 	else
-		ts-sysstat -o "${OUTPUT_DIR}/sysstat" &
+		ts sysstat -o "${OUTPUT_DIR}/sysstat" &
 	fi
 fi
 
@@ -263,12 +263,12 @@ dbt3-$DATABASE-create-tables $TABLESPACE_FLAG || exit 1
 
 if [ $STATS -eq 1 ]; then
 	# Collect database statistics
-	if ! which "ts-${DATABASE}-stat" > /dev/null 2>&1; then
+	if ! which ts > /dev/null 2>&1; then
 		printf "WARNING: %s not found for database stats " \
-				"ts-${DATABASE}-stat"
+				"ts ${DATABASE}-stat"
 		echo "collection"
 	else
-		eval "ts-${DATABASE}-stat -o ${OUTPUT_DIR}/dbstat &"
+		eval "ts ${DATABASE}-stat -o ${OUTPUT_DIR}/dbstat &"
 	fi
 fi
 
@@ -277,7 +277,7 @@ s_time=`date +%s`
 dbt3-$DATABASE-time-statistics -s -n LOAD || exit 1
 
 if [ $PROFILE -eq 1 ]; then
-	ts-profile -o "${OUTPUT_DIR}/profile" sleep 1 &
+	ts profile -o "${OUTPUT_DIR}/profile" sleep 1 &
 fi
 
 eval "dbt3-${DATABASE}-load-data -C ${CHUNKS} -o ${OUTPUT_DIR} \
@@ -301,5 +301,5 @@ if [ $MPP -eq 1 ]; then
 fi
 
 if [ $PROFILE -eq 1 ]; then
-	ts-profile -o "${OUTPUT_DIR}/profile" -p
+	ts profile -o "${OUTPUT_DIR}/profile" -p
 fi
diff --git a/scripts/dbt3-power-test.in b/scripts/dbt3-power-test.in
--- a/scripts/dbt3-power-test.in
+++ b/scripts/dbt3-power-test.in
@@ -56,11 +56,11 @@ EOF
 }
 
 stop_procs() {
-	if which ts-sysstat > /dev/null 2>&1; then
-		ts-sysstat -o "${OUTPUT_DIR}/sysstat" -s &
+	if which ts > /dev/null 2>&1; then
+		ts sysstat -o "${OUTPUT_DIR}/sysstat" -s &
 	fi
-	if which "ts-${DATABASE}-stat" > /dev/null 2>&1; then
-		eval "ts-${DATABASE}-stat -o ${OUTPUT_DIR}/dbstat -s &"
+	if which ts > /dev/null 2>&1; then
+		eval "ts ${DATABASE}-stat -o ${OUTPUT_DIR}/dbstat -s &"
 	fi
 }
 trap 'stop_procs' INT TERM
@@ -213,19 +213,17 @@ fi
 
 if [ $STATS -eq 1 ]; then
 	# Start collecting system statistics.
-	if ! which ts-sysstat > /dev/null 2>&1; then
-		echo "WARNING: ts-sysstat not found for system stats collection"
+	if ! which ts > /dev/null 2>&1; then
+		echo "WARNING: ts not found for system stats collection"
 	else
-		ts-sysstat -o "${OUTPUT_DIR}/sysstat" &
+		ts sysstat -o "${OUTPUT_DIR}/sysstat" &
 	fi
 
 	# Collect database statistics
-	if ! which "ts-${DATABASE}-stat" > /dev/null 2>&1; then
-		printf "WARNING: %s not found for database stats " \
-				"ts-${DATABASE}-stat"
-		echo "collection"
+	if ! which ts > /dev/null 2>&1; then
+		echo "WARNING: ts not found for database stats collection"
 	else
-		eval "ts-${DATABASE}-stat -o ${OUTPUT_DIR}/dbstat &"
+		eval "ts ${DATABASE}-stat -o ${OUTPUT_DIR}/dbstat &"
 	fi
 fi
 
@@ -258,11 +256,11 @@ while [ ${i} -le 22 ]; do
 	if [ $PROFILE -eq 1 ]; then
 		PERFDIR="${OUTPUT_DIR}/profile/${N}"
 		if [ $MPP -eq 0 ]; then
-			ts-profile -o "${PERFDIR}" sleep 1 &
+			ts profile -o "${PERFDIR}" sleep 1 &
 		else
 			for HOSTNAME in ${coordMasterServers[*]} ${datanodeMasterServers[*]}; do
 				ssh $HOSTNAME << __EOF__ &
-ts-profile -o "${PERFDIR}" sleep 1 &
+ts profile -o "${PERFDIR}" sleep 1 &
 __EOF__
 			done
 			fi
@@ -326,7 +324,7 @@ if [ $PROFILE -eq 1 ]; then
 		i=1
 		while [ $i -le 22 ]; do
 			PERFDIR="${OUTPUT_DIR}/profile/${i}"
-			ts-profile -o "${PERFDIR}" -p
+			ts profile -o "${PERFDIR}" -p
 			i=$(( $i + 1 ))
 		done > "${OUTPUT_DIR}/profile/report-output.txt" 2>&1
 	else
@@ -336,7 +334,7 @@ if [ $PROFILE -eq 1 ]; then
 				PERFDIR="${OUTPUT_DIR}/profile/${i}"
 				PERFPREFIX=q$i
 				ssh $HOSTNAME << __EOF__ &
-ts-profile -o "${PERFDIR}" -p
+ts profile -o "${PERFDIR}" -p
 __EOF__
 				i=$(( $i + 1 ))
 			done > "${OUTPUT_DIR}/profile/report-output.txt" 2>&1
diff --git a/scripts/dbt3-throughput-test.in b/scripts/dbt3-throughput-test.in
--- a/scripts/dbt3-throughput-test.in
+++ b/scripts/dbt3-throughput-test.in
@@ -52,11 +52,11 @@ EOF
 }
 
 stop_procs() {
-	if which ts-sysstat > /dev/null 2>&1; then
-		ts-sysstat -o "${OUTPUT_DIR}/sysstat" -s &
+	if which ts > /dev/null 2>&1; then
+		ts sysstat -o "${OUTPUT_DIR}/sysstat" -s &
 	fi
-	if which "ts-${DATABASE}-stat" > /dev/null 2>&1; then
-		eval "ts-${DATABASE}-stat -o ${OUTPUT_DIR}/dbstat -s &"
+	if which ts > /dev/null 2>&1; then
+		eval "ts ${DATABASE}-stat -o ${OUTPUT_DIR}/dbstat -s &"
 	fi
 }
 trap 'stop_procs' INT TERM
@@ -164,25 +164,23 @@ dbt3-$TAG-time-statistics -s -n PERF.THRUPUT || exit 1
 
 # Start collecting system statistics. 
 if [ $STATS -eq 1 ]; then
-	if ! which ts-sysstat > /dev/null 2>&1; then
-		echo "WARNING: ts-sysstat not found for system stats collection"
+	if ! which ts > /dev/null 2>&1; then
+		echo "WARNING: ts not found for system stats collection"
 	else
-		ts-sysstat -o "${OUTPUT_DIR}/sysstat" &
+		ts sysstat -o "${OUTPUT_DIR}/sysstat" &
 	fi
 
 	# Collect database statistics
-	if ! which "ts-${DATABASE}-stat" > /dev/null 2>&1; then
-		printf "WARNING: %s not found for database stats " \
-				"ts-${DATABASE}-stat"
-		echo "collection"
+	if ! which ts > /dev/null 2>&1; then
+		echo "WARNING: ts not found for database stats collection"
 	else
-		eval "ts-${DATABASE}-stat -o ${OUTPUT_DIR}/dbstat &"
+		eval "ts ${DATABASE}-stat -o ${OUTPUT_DIR}/dbstat &"
 	fi
 fi
 
 if [ "${MPP}" -eq 0 ] && [ "${PROFILE}" -eq 1 ]; then
 	PERFDIR="${OUTPUT_DIR}/profile"
-	ts-profile -o "${PERFDIR}" sleep 1 &
+	ts profile -o "${PERFDIR}" sleep 1 &
 fi
 
 # Start the streams.
@@ -203,5 +201,5 @@ fi
 
 if [ "${MPP}" -eq 0 ] && [ "${PROFILE}" -eq 1 ]; then
 	echo "Generating profiling reports for throughput test..."
-	ts-profile -o "${PERFDIR}" -p
+	ts profile -o "${PERFDIR}" -p
 fi
