Add support of Postgres-XL

diff --git a/scripts/dbt3-sysstats b/scripts/dbt3-sysstats
--- a/scripts/dbt3-sysstats
+++ b/scripts/dbt3-sysstats
@@ -7,6 +7,28 @@
 #               2002-2014 Mark Wong
 #               2014      2ndQuadrant, Ltd.
 
+start_remote_pidstat()
+{
+	HOST=$1
+
+	PIDSTATFILE="$OUTPUT_DIR/$HOST/pidstat.txt"
+	ssh $HOST << __EOF__
+mkdir -p $SARDIR
+$PIDSTAT $SAMPLE_LENGTH > $PIDSTATFILE
+__EOF__
+}
+
+start_remote_sar()
+{
+	HOST=$1
+
+	SARDIR="$OUTPUT_DIR/$HOST"
+	ssh $HOST << __EOF__
+mkdir -p $SARDIR
+$SAR -o $SARDIR/sar_raw.out $SAMPLE_LENGTH > $SARDIR/sar.txt
+__EOF__
+}
+
 if [ $# -lt 1 ]; then
     echo "usage: $0 --outdir <output_dir> -sample <sample_length>"
     echo "	<output_dir> will be created if it doesn't exist"
@@ -25,12 +47,22 @@ fi
 
 which pidstat > /dev/null 2>&1
 if [ $? -eq 0 ]; then
-    PIDSTAT=pidstat
+    PIDSTAT="pidstat -h -l -d -r -s -u -w"
+	$PIDSTAT 1 1 > /dev/null 2>&1
+	if [ $? -ne 0 ]; then
+		PIDSTAT="pidstat -h -l -d -r -u -w"
+		$PIDSTAT 1 1 > /dev/null 2>&1
+		if [ $? -ne 0 ]; then
+			echo "WARNING: Cannot determine propper pidstat flags"
+			PIDSTAT="true"
+		fi
+	fi
 else
     PIDSTAT=true
 fi
 
 COUNTER=0
+MPP=0
 
 while :
 do
@@ -71,6 +103,9 @@ do
 	--dbname)
 		DBTYPE_NAME=$optarg
 		;;
+	--mpp)
+		MPP=1
+		;;
 	--outdir)
 		OUTPUT_DIR=$optarg
 		;;
@@ -96,8 +131,31 @@ mkdir -p $OUTPUT_DIR
 echo "starting system statistics data collection"
 
 # collect all sar data in binary form
-${SAR} -o ${OUTPUT_DIR}/sar_raw.out ${SAMPLE_LENGTH} > ${OUTPUT_DIR}/sar.txt &
-echo "$!" > ${OUTPUT_DIR}/sar.pid
+if [ $MPP -eq 0 ]; then
+	$SAR -o $OUTPUT_DIR/sar_raw.out $SAMPLE_LENGTH > $OUTPUT_DIR/sar.txt &
+	echo "$!" > $OUTPUT_DIR/sar.pid
 
-${PIDSTAT} -h -l -d -r -s -u -w ${SAMPLE_LENGTH} > ${OUTPUT_DIR}/pidstat.txt &
-echo "$!" > ${OUTPUT_DIR}/pidstat.pid
+	$PIDSTAT $SAMPLE_LENGTH > $OUTPUT_DIR/pidstat.txt &
+	echo "$!" > ${OUTPUT_DIR}/pidstat.pid
+else
+	SARDIR="$OUTPUT_DIR/$GTMHOST"
+	mkdir -p $SARDIR
+	$SAR -o $SARDIR/sar_raw.out $SAMPLE_LENGTH > $SARDIR/sar.txt &
+	SARPIDS="$!"
+
+	for HOSTNAME in $HOSTNAMES; do
+		start_remote_sar $HOSTNAME &
+		SARPIDS="$SARPIDS $!"
+	done
+
+	echo $SARPIDS > $OUTPUT_DIR/sar.pid
+
+	PIDSTATFILE="$OUTPUT_DIR/$GTMHOST/pidstat.txt"
+
+	$PIDSTAT $SAMPLE_LENGTH > $PIDSTATFILE &
+	PIDSTATPIDS="$!"
+	for HOSTNAME in $HOSTNAMES; do
+		start_remote_pidstat $HOSTNAME &
+		PIDSTATPIDS="$PIDSTATPIDS $!"
+	done
+fi
