Stop making pdf reports by default

diff --git a/scripts/dbt3-generate-report.in b/scripts/dbt3-generate-report.in
--- a/scripts/dbt3-generate-report.in
+++ b/scripts/dbt3-generate-report.in
@@ -252,28 +252,30 @@ for RST in $(find $INDIR -name "*.rst"); do
 	ls -1v ${INDIR}/*.html
 	echo ""
 
-	# A pdf could be produced other ways, but I believe pandoc produces the most
-	# minimally styled LaTeX looking document, as opposed to using rst2latex,
-	# with default settings.
-	which pandoc > /dev/null 2>&1
-	if [ $? -eq 0 ]; then
-		(cd $INDIR && \
-				pandoc -s report.html -f html -t pdf -o report.pdf \
-						2> /dev/null)
-		for HTML in $(find $INDIR -name "*.html"); do
-			NAME="${HTML%.*}"
-			(cd $(dirname $HTML) && \
-					pandoc -s $(basename $HTML) -f html -t pdf -o ${NAME}.pdf \
-							2> /dev/null) &
-		done
-		wait
+	if [ $GENERATE_PDF -eq 1 ]; then
+		# A pdf could be produced other ways, but I believe pandoc produces the
+		# most minimally styled LaTeX looking document, as opposed to using
+		# rst2latex, with default settings.
+		which pandoc > /dev/null 2>&1
+		if [ $? -eq 0 ]; then
+			(cd $INDIR && \
+					pandoc -s report.html -f html -t pdf -o report.pdf \
+							2> /dev/null)
+			for HTML in $(find $INDIR -name "*.html"); do
+				NAME="${HTML%.*}"
+				(cd $(dirname $HTML) && \
+						pandoc -s $(basename $HTML) -f html -t pdf -o ${NAME}.pdf \
+								2> /dev/null) &
+			done
+			wait
 
-		echo "Generated top level PDF reports:"
-		ls -1v ${INDIR}/*.pdf
-		echo ""
-	else
-		echo "pandoc required to generate pdf report"
-		exit 1
+			echo "Generated top level PDF reports:"
+			ls -1v ${INDIR}/*.pdf
+			echo ""
+		else
+			echo "pandoc required to generate pdf report"
+			exit 1
+		fi
 	fi
 else
 	echo "rst2html5 required to generate html report"
