Replace custom stats and profile collection with touchstone-tools
Hopefully simplifies maintenance of the scripts.  Some other notable
changes:

* profile the throughput test as a whole, not per stream, since it's
  profiling system-wide
* collect only 1 second of profile data as opposed to the entire
  duration of the test

diff --git a/scripts/dbt3-load-test.in b/scripts/dbt3-load-test.in
--- a/scripts/dbt3-load-test.in
+++ b/scripts/dbt3-load-test.in
@@ -10,6 +10,9 @@
 #               2005-2022 Mark Wong
 #
 
+trap 'ts-sysstat -o "${OUTPUT_DIR}/sysstat" -s; \
+		eval "ts-${DATABASE}-stat -o ${OUTPUT_DIR}/dbstat -s"' INT TERM
+
 usage()
 {
 	echo
@@ -29,9 +32,9 @@ usage()
 	echo "  -l              only load data"
 	echo "  -o DIRECTORY    path to store test results"
 	echo "  -R              materialized view mode"
+	echo "  -S              enable system and database stats collection"
 	echo "  -U              run test as an unprivileged user"
-	echo "  -y              enable oprofile (Linux only)"
-	echo "  -Y              enable linux perf (Linux only)"
+	echo "  -Y              enable profiling (Linux only)"
 	echo ""
 	echo "DBMS options are:"
 	echo "  monetdb         MonetDB"
@@ -44,19 +47,29 @@ usage()
 	echo "  -p              database parameters for the load test"
 }
 
+stop_procs() {
+	if which ts-sysstat > /dev/null 2>&1; then
+		ts-sysstat -o "${OUTPUT_DIR}/sysstat" -s &
+	fi
+	if which "ts-${DATABASE}-stat" > /dev/null 2>&1; then
+		eval "ts-${DATABASE}-stat -o ${OUTPUT_DIR}/dbstat -s &"
+	fi
+}
+trap 'stop_procs' INT TERM
+
 DIRECT_LOAD=0
 DIRECT_LOAD_ARG=""
 GENERATE=0
 MPP=0
 ONLY_LOAD=0
 PRIVILEGED=1
+PROFILE=0
 RESORT=0
 SF=0
-USE_OPROFILE=0
-USE_LINUXPERF=0
+STATS=0
 WORKLOAD="H"
 
-while getopts "a:cC:df:g:lo:p:RtUyY:" opt; do
+while getopts "a:cC:df:g:lo:p:RStUY" opt; do
 	case $opt in
 	a)
 		DATABASE=$OPTARG
@@ -97,15 +110,15 @@ while getopts "a:cC:df:g:lo:p:RtUyY:" opt; do
 	t)
 		TABLESPACE_FLAG="-t -b"
 		;;
+	S)
+		STATS=1
+		;;
 	U)
 		PRIVILEGED=0
 		UNPRIVILEGED_ARG="-U"
 		;;
-	y)
-		USE_OPROFILE=1
-		;;
 	Y)
-		USE_LINUXPERF=1
+		PROFILE=1
 		;;
 	\?)
 		echo "Usage: $0 [-o <dir> -p <db_param> -f <scale_factor>]"
@@ -212,8 +225,14 @@ else
 	echo "Creating the database using existing data files."
 fi
 
-# Start collecting system statistics.
-dbt3-sysstats --outdir $OUTPUT_DIR --sample 60 --mpp $MPP || exit 1
+if [ $STATS -eq 1 ]; then
+	# Start collecting system statistics.
+	if ! which ts-sysstat > /dev/null 2>&1; then
+		echo "WARNING: ts-sysstat not found for system stats collection"
+	else
+		ts-sysstat -o "${OUTPUT_DIR}/sysstat" &
+	fi
+fi
 
 if [ $PRIVILEGED -eq 1 ]; then
 	eval dbt3-$DATABASE-create-db -o $OUTPUT_DIR $PARAMETERS_ARG
@@ -222,43 +241,35 @@ fi
 dbt3-$DATABASE-drop-tables || exit 1
 dbt3-$DATABASE-create-tables $TABLESPACE_FLAG || exit 1
 
+if [ $STATS -eq 1 ]; then
+	# Collect database statistics
+	if ! which "ts-${DATABASE}-stat" > /dev/null 2>&1; then
+		printf "WARNING: %s not found for database stats " \
+				"ts-${DATABASE}-stat"
+		echo "collection"
+	else
+		eval "ts-${DATABASE}-stat -o ${OUTPUT_DIR}/dbstat &"
+	fi
+fi
+
 echo "Load Test starting at `date`"
 s_time=`date +%s`
 dbt3-$DATABASE-time-statistics -s -n LOAD || exit 1
 
-# Collect database statistics
-dbt3-$DATABASE-dbstat $OUTPUT_DIR 2> /dev/null &
-
-# Initialize profile counters.
-if [ -f /proc/profile ]; then
-	clearprof
+if [ $PROFILE -eq 1 ]; then
+	ts-profile -o "${OUTPUT_DIR}/profile" sleep 1 &
 fi
 
-if [ $USE_OPROFILE -eq 1 ]; then
-	clearoprof
-fi
-
-if [ $USE_LINUXPERF -eq 1 ]; then
-	PERFDIR=$OUTPUT_DIR/perf
-	mkdir -p $PERFDIR
-	PERFCOMMAND="perf record -a -g -s -F 100 -o $PERFDIR/perf.data"
-fi
-
-eval $PERFCOMMAND dbt3-${DATABASE}-load-data -C $CHUNKS $DIRECT_LOAD_ARG $UNPRIVILEGED_ARG || exit 1
+"dbt3-${DATABASE}-load-data" -C "${CHUNKS}" "${DIRECT_LOAD_ARG}" \
+		"${UNPRIVILEGED_ARG}" || exit 1
 
 dbt3-$DATABASE-time-statistics -e -n LOAD || exit 1
 e_time=`date +%s`
 diff_time=`expr $e_time - $s_time`
 echo "Elapsed time for Load Test : $diff_time seconds"
 
-# Stop collecting system statistics.
-read SARPID < $OUTPUT_DIR/sar.pid
-kill $SARPID
-read PIDSTATPID < $OUTPUT_DIR/pidstat.pid
-kill $PIDSTATPID
-if [ -f "$OUTPUT_DIR/dbstat.pid" ]; then
-	read DBSTATPID < $OUTPUT_DIR/dbstat.pid
-	kill $DBSTATPID
+if [ $STATS -eq 1 ]; then
+	stop_procs
 fi
 
 # Brute force.
@@ -268,28 +279,6 @@ if [ $MPP -eq 1 ]; then
 	done
 fi
 
-# Collect profile data.
-if [ -f /proc/profile ]; then
-	profname='Load_Test'
-	getprof
-fi
-
-if [ $USE_OPROFILE -eq 1 ]; then
-	profname='Load_Test'
-	getoprof
-fi
-
-if [ $USE_LINUXPERF -eq 1 ]; then
-	# Sometimes perf segfaults if it's running more than once.
-	echo "Generating Linux perf reports for load test..."
-	perf report -i $PERFDIR/perf.data -n > $PERFDIR/perf-report.txt \
-			2>> $OUTPUT_DIR/perf/report-output.txt
-	$GZIP $OUTPUT_DIR/perf/perf-report.txt
-	perf annotate -l -P -i $PERFDIR/perf.data > $PERFDIR/perf-annotate.txt \
-			2>> $OUTPUT_DIR/perf/report-output.txt
-	$GZIP $OUTPUT_DIR/perf/perf-annotate.txt
-	perf script -L -i $PERFDIR/perf.data > $PERFDIR/perf-trace.txt \
-			2>> $OUTPUT_DIR/perf/report-output.txt
-	$GZIP $OUTPUT_DIR/perf/perf-trace.txt
-	$GZIP $PERFDIR/perf.data
+if [ $PROFILE -eq 1 ]; then
+	ts-profile -o "${OUTPUT_DIR}/profile" -p
 fi
diff --git a/scripts/dbt3-power-test.in b/scripts/dbt3-power-test.in
--- a/scripts/dbt3-power-test.in
+++ b/scripts/dbt3-power-test.in
@@ -11,11 +11,11 @@
 
 EXTRA=0
 EXTRA_ARGS=
-USE_OPROFILE=0
-USE_LINUXPERF=0
 NO_REFRESH=0
 MPP=0
 PRIVILEGED=1
+PROFILE=0
+STATS=0
 
 usage()
 {
@@ -34,9 +34,9 @@ usage()
 	echo "  -l              only load data"
 	echo "  -o DIRECTORY    path to store test results"
 	echo "  -s SEED         seed to use for power and throughput tests"
+	echo "  -S              enable system and database stats collection"
 	echo "  -U              run as an unprivileged user"
-	echo "  -y              enable oprofile (Linux only)"
-	echo "  -Y              enable linux perf (Linux only)"
+	echo "  -Y              enable software profiling (Linux only)"
 	echo "  -z              do not run refresh streams"
 	echo ""
 	echo "DBMS options are:"
@@ -51,8 +51,18 @@ usage()
 	echo "  -p              database parameters for the load test"
 }
 
+stop_procs() {
+	if which ts-sysstat > /dev/null 2>&1; then
+		ts-sysstat -o "${OUTPUT_DIR}/sysstat" -s &
+	fi
+	if which "ts-${DATABASE}-stat" > /dev/null 2>&1; then
+		eval "ts-${DATABASE}-stat -o ${OUTPUT_DIR}/dbstat -s &"
+	fi
+}
+trap 'stop_procs' INT TERM
+
 # process the command line parameters
-while getopts "a:ef:o:p:s:UyYz" opt; do
+while getopts "a:ef:o:p:s:SUYz" opt; do
 	case $opt in
 	a)
 		DATABASE=$OPTARG
@@ -79,15 +89,15 @@ while getopts "a:ef:o:p:s:UyYz" opt; do
 	s)
 		SEED_FILE=$OPTARG
 		;;
+	S)
+		STATS=1
+		;;
 	U)
 		PRIVILEGED=0
 		UNPRIVILEGED_ARG="-U"
 		;;
-	y)
-		USE_OPROFILE=1
-		;;
 	Y)
-		USE_LINUXPERF=1
+		PROFILE=1
 		;;
 	z)
 		NO_REFRESH=1
@@ -180,20 +190,22 @@ if [ $PRIVILEGED -eq 1 ]; then
 	eval dbt3-$DATABASE-start-db -o $OUTPUT_DIR $PARAMETERS_ARG || exit 1
 fi
 
-# Start collecting system statistics.
-dbt3-sysstats --outdir $OUTPUT_DIR --sample 60 --mpp $MPP || exit 1
+if [ $STATS -eq 1 ]; then
+	# Start collecting system statistics.
+	if ! which ts-sysstat > /dev/null 2>&1; then
+		echo "WARNING: ts-sysstat not found for system stats collection"
+	else
+		ts-sysstat -o "${OUTPUT_DIR}/sysstat" &
+	fi
 
-# Collect database statistics
-dbt3-$DATABASE-dbstat ${OUTPUT_DIR} &
-
-# Clear the read profile counters.
-if [ -f /proc/profile ]; then
-	clearprof
-fi
-
-# Clear the oprofile counters.
-if [ $USE_OPROFILE -eq 1 ]; then
-	clearoprof
+	# Collect database statistics
+	if ! which "ts-${DATABASE}-stat" > /dev/null 2>&1; then
+		printf "WARNING: %s not found for database stats " \
+				"ts-${DATABASE}-stat"
+		echo "collection"
+	else
+		eval "ts-${DATABASE}-stat -o ${OUTPUT_DIR}/dbstat &"
+	fi
 fi
 
 s_time_power=`date +%s`
@@ -222,16 +234,14 @@ i=1
 while [ ${i} -le 22 ]; do
 	Q=$(eval "\"${QGEN}\" -c -r ${SEED} -p 0 -s ${SCALE_FACTOR} ${QGEN_ARG} ${i}")
 	N=`echo ${Q} | sed -n -r 's/.*\(#\)([[:digit:]]+)\..*/\1/p'`
-	if [ $USE_LINUXPERF -eq 1 ]; then
-		PERFDIR=$OUTPUT_DIR/perf/$N
+	if [ $PROFILE -eq 1 ]; then
+		PERFDIR="${OUTPUT_DIR}/profile/${N}"
 		if [ $MPP -eq 0 ]; then
-			mkdir -p $PERFDIR
-			PERFCOMMAND="perf record -a -g -s -F 100 -o $PERFDIR/q$N-perf.data"
+			ts-profile -o "${PERFDIR}" sleep 1 &
 		else
 			for HOSTNAME in ${coordMasterServers[*]} ${datanodeMasterServers[*]}; do
 				ssh $HOSTNAME << __EOF__ &
-mkdir -p $PERFDIR
-perf record -a -g -s -F 100 -o $PERFDIR/perf-$HOSTNAME-q$N.data
+ts-profile -o "${PERFDIR}" sleep 1 &
 __EOF__
 			done
 			fi
@@ -250,12 +260,6 @@ __EOF__
 	fi
 
 	dbt3-$TAG-time-statistics -e -n $TASK || exit 1
-	if [ $MPP -eq 1 ] && [ $USE_LINUXPERF -eq 1 ]; then
-		# Brute force.
-		for HOSTNAME in ${coordMasterServers[*]} ${datanodeMasterServers[*]}; do
-			ssh $HOSTNAME "killall -9 perf"
-		done
-	fi
 
 	i=$(( ${i} + 1 ))
 done
@@ -280,18 +284,8 @@ echo "`date`: Power Test completed."
 diff_time=$(( $e_time_power - $s_time_power ))
 echo "Elapsed time for Power Test : $diff_time seconds"
 
-# Stop collecting system statistics.
-read SARPIDS < $OUTPUT_DIR/sar.pid
-for SARPID in $SARPIDS; do
-	kill $SARPID
-done
-read PIDSTATPIDS < $OUTPUT_DIR/pidstat.pid
-for PIDSTATPID in $PIDSTATPIDS; do
-	kill $PIDSTATPID
-done
-if [ -f "$OUTPUT_DIR/dbstat.pid" ]; then
-	read DBSTATPID < $OUTPUT_DIR/dbstat.pid
-	kill $DBSTATPID
+if [ $STATS -eq 1 ]; then
+	stop_procs
 fi
 
 # Brute force.
@@ -305,55 +299,26 @@ if [ $PRIVILEGED -eq 1 ]; then
 	dbt3-$DATABASE-stop-db || exit 1
 fi
 
-if [ -f /proc/profile ]; then
-	profname="Power_Test"
-	getprof
-fi
-
-if [ $USE_OPROFILE -eq 1 ]; then
-	profname="Power_Test"
-	getoprof
-fi
-
-if [ $USE_LINUXPERF -eq 1 ]; then
-	echo "Generating Linux perf reports for power test..."
+if [ $PROFILE -eq 1 ]; then
+	echo "Generating profilig reports for power test..."
 	if [ $MPP -eq 0 ]; then
 		i=1
 		while [ $i -le 22 ]; do
-			PERFDIR=$OUTPUT_DIR/perf/$i
-			PERFPREFIX=q$i
-			perf report -i $PERFDIR/$PERFPREFIX-perf.data -n \
-					> $PERFDIR/$PERFPREFIX-perf-report.txt
-			$GZIP $PERFDIR/$PERFPREFIX-perf-report.txt
-			perf annotate -l -P -i $PERFDIR/$PERFPREFIX-perf.data \
-					> $PERFDIR/$PERFPREFIX-perf-annotate.txt
-			$GZIP $PERFDIR/$PERFPREFIX-perf-annotate.txt
-			perf script -L -i $PERFDIR/$PERFPREFIX-perf.data \
-					> $PERFDIR/$PERFPREFIX-perf-trace.txt
-			$GZIP $PERFDIR/$PERFPREFIX-perf-trace.txt
-			$GZIP $PERFDIR/$PERFPREFIX-perf.data
+			PERFDIR="${OUTPUT_DIR}/profile/${i}"
+			ts-profile -o "${PERFDIR}" -p
 			i=$(( $i + 1 ))
-		done > $OUTPUT_DIR/perf/report-output.txt 2>&1
+		done > "${OUTPUT_DIR}/profile/report-output.txt" 2>&1
 	else
 		for HOSTNAME in ${coordMasterServers[*]} ${datanodeMasterServers[*]}; do
 			i=1
 			while [ $i -le 22 ]; do
-				PERFDIR=$OUTPUT_DIR/perf/$i
+				PERFDIR="${OUTPUT_DIR}/profile/${i}"
 				PERFPREFIX=q$i
 				ssh $HOSTNAME << __EOF__ &
-perf report -i $PERFDIR/perf-$HOSTNAME-$PERFPREFIX.data -n \
-		> $PERFDIR/perf-report-$HOSTNAME-$PERFPREFIX.txt
-$GZIP $PERFDIR/perf-report-$HOSTNAME-$PERFPREFIX.txt
-perf annotate -l -P -i $PERFDIR/perf-$HOSTNAME-$PERFPREFIX.data \
-		> $PERFDIR/perf-annotate-$HOSTNAME-$PERFPREFIX.txt
-$GZIP $PERFDIR/perf-annotate-$HOSTNAME-$PERFPREFIX.txt
-perf script -L -i $PERFDIR/perf-$HOSTNAME-$PERFPREFIX.data \
-		> $PERFDIR/perf-trace-$HOSTNAME-$PERFPREFIX.txt
-$GZIP $PERFDIR/perf-trace-$HOSTNAME-$PERFPREFIX.txt
-$GZIP $PERFDIR/perf-$HOSTNAME-$PERFPREFIX.data
+ts-profile -o "${PERFDIR}" -p
 __EOF__
 				i=$(( $i + 1 ))
-			done > $OUTPUT_DIR/perf/report-output.txt 2>&1
+			done > "${OUTPUT_DIR}/profile/report-output.txt" 2>&1
 		done
 	wait
 	fi
diff --git a/scripts/dbt3-throughput-test.in b/scripts/dbt3-throughput-test.in
--- a/scripts/dbt3-throughput-test.in
+++ b/scripts/dbt3-throughput-test.in
@@ -15,8 +15,7 @@ NO_REFRESH=0
 NO_REFRESH_FLAG=
 PRIVILEGED=1
 EXTRA_ARGS=
-USE_OPROFILE=0
-USE_LINUXPERF=0
+STATS=0
 
 usage()
 {
@@ -33,10 +32,10 @@ usage()
 	echo "  -n STREAMS      number of throughput streams"
 	echo "  -o DIRECTORY    path to store test results"
 	echo "  -s SEED         seed to use for power and throughput tests"
+	echo "  -S              enable system and database stats collection"
 	echo "  -u              use tablespaces"
 	echo "  -U              run test as an unprivileged user"
-	echo "  -y              enable oprofile (Linux only)"
-	echo "  -Y              enable linux perf (Linux only)"
+	echo "  -Y              enable software profiling (Linux only)"
 	echo "  -z              do not run refresh streams"
 	echo ""
 	echo "DBMS options are:"
@@ -51,7 +50,17 @@ usage()
 	echo "  -p              database parameters for the load test"
 }
 
-while getopts "a:ef:hn:o:p:s:UyYz" opt; do
+stop_procs() {
+	if which ts-sysstat > /dev/null 2>&1; then
+		ts-sysstat -o "${OUTPUT_DIR}/sysstat" -s &
+	fi
+	if which "ts-${DATABASE}-stat" > /dev/null 2>&1; then
+		eval "ts-${DATABASE}-stat -o ${OUTPUT_DIR}/dbstat -s &"
+	fi
+}
+trap 'stop_procs' INT TERM
+
+while getopts "a:ef:hn:o:p:s:SUz" opt; do
 	case $opt in
 	a) DATABASE=$OPTARG
 		if [ "x$DATABASE" = "xpgxl" ]; then
@@ -75,13 +84,12 @@ while getopts "a:ef:hn:o:p:s:UyYz" opt; do
 		;;
 	s) SEED_FILE=$OPTARG
 		;;
+	S) STATS=1
+		;;
 	U) PRIVILEGED=0
 		UNPRIVILEGED_ARG="-U"
 		;;
-	y) USE_OPROFILE=1
-		;;
-	Y) USE_LINUXPERF=1
-		LINUXPERF_FLAG="-Y"
+	Y) PROFILE=1
 		;;
 	z) NO_REFRESH_FLAG="-z"
 		NO_REFRESH=1
@@ -119,22 +127,6 @@ echo "Seed : $SEED" > $OUTPUT_DIR/readme.txt
 RUNDIR=$OUTPUT_DIR/run
 mkdir -p $RUNDIR
 
-# Clear the read profile counters.
-if [ -f /proc/profile ]; then
-	clearprof
-fi
-
-# Clear the oprofile counters.
-if [ $USE_OPROFILE -eq 1 ]; then
-	clearoprof
-fi
-
-if [ $MPP -eq 0 ] && [ $USE_LINUXPERF -eq 1 ]; then
-	PERFDIR=$OUTPUT_DIR/perf
-	mkdir -p $PERFDIR
-	PERFCOMMAND="perf record -a -g -s -F 100 -o $PERFDIR/perf.data"
-fi
-
 if [ $PRIVILEGED -eq 1 ]; then
 	dbt3-$DATABASE-stop-db
 	eval dbt3-$DATABASE-start-db -o $OUTPUT_DIR $PARAMETERS_ARG || exit 1
@@ -143,79 +135,45 @@ fi
 dbt3-$TAG-time-statistics -s -n PERF.THRUPUT || exit 1
 
 # Start collecting system statistics. 
-dbt3-sysstats --outdir $OUTPUT_DIR --sample 60 || exit 1
+if [ $STATS -eq 1 ]; then
+	if ! which ts-sysstat > /dev/null 2>&1; then
+		echo "WARNING: ts-sysstat not found for system stats collection"
+	else
+		ts-sysstat -o "${OUTPUT_DIR}/sysstat" &
+	fi
 
-# Start collecting database statistics.
-dbt3-$DATABASE-dbstat ${OUTPUT_DIR} &
-
-# Start the streams.
-eval $PERFCOMMAND dbt3-throughput-stream-wrapper -f $scale_factor \
-		-n $num_stream $EXTRA_ARGS -o $OUTPUT_DIR -s $SEED_FILE \
-		$NO_REFRESH_FLAG $LINUXPERF_FLAG $UNPRIVILEGED_ARG || exit 1
-
-# Stop collecting system statistics.
-read SARPIDS < $OUTPUT_DIR/sar.pid
-for SARPID in $SARPIDS; do
-	kill $SARPID
-done
-read PIDSTATPIDS < $OUTPUT_DIR/pidstat.pid
-for PIDSTATPID in $PIDSTATPIDS; do
-	kill $PIDSTATPID
-done
-if [ -f "$OUTPUT_DIR/dbstat.pid" ]; then
-	read DBSTATPID < $OUTPUT_DIR/dbstat.pid
-	kill $DBSTATPID
+	# Collect database statistics
+	if ! which "ts-${DATABASE}-stat" > /dev/null 2>&1; then
+		printf "WARNING: %s not found for database stats " \
+				"ts-${DATABASE}-stat"
+		echo "collection"
+	else
+		eval "ts-${DATABASE}-stat -o ${OUTPUT_DIR}/dbstat &"
+	fi
 fi
 
+if [ "${MPP}" -eq 0 ] && [ "${PROFILE}" -eq 1 ]; then
+	PERFDIR="${OUTPUT_DIR}/profile"
+	ts-profile -o "${PERFDIR}" sleep 1 &
+fi
+
+# Start the streams.
+eval "dbt3-throughput-stream-wrapper -f $scale_factor \
+		-n $num_stream $EXTRA_ARGS -o $OUTPUT_DIR -s $SEED_FILE \
+		$NO_REFRESH_FLAG $UNPRIVILEGED_ARG" || exit 1
+
 dbt3-$TAG-time-statistics -e -n PERF.THRUPUT || exit 1
+
+if [ $STATS -eq 1 ]; then
+	stop_procs
+fi
 
 # Stop the database after the test.
 if [ $PRIVILEGED -eq 1 ]; then
 	dbt3-$DATABASE-stop-db
 fi
 
-if [ -f /proc/profile ]; then
-	profname="Throughput_Test"
-	getprof
-fi
-
-if [ $USE_OPROFILE -eq 1 ]; then
-	profname="Throughput_Test"
-	getoprof
-fi
-
-if [ $MPP -eq 0 ] && [ $USE_LINUXPERF -eq 1 ]; then
-	echo "Generating Linux perf reports for throughput test..."
-	perf report -i $PERFDIR/perf.data -n > $PERFDIR/perf-report.txt \
-			2>> $OUTPUT_DIR/perf/report-output.txt
-	$GZIP $PERFDIR/perf-report.txt
-	perf annotate -l -P -i $PERFDIR/perf.data > $PERFDIR/perf-annotate.txt \
-			2>> $OUTPUT_DIR/perf/report-output.txt
-	$GZIP $PERFDIR/perf-annotate.txt
-	perf script -L -i $PERFDIR/perf.data > $PERFDIR/perf-trace.txt \
-			2>> $OUTPUT_DIR/perf/report-output.txt
-	$GZIP $PERFDIR/perf-trace.txt
-	$GZIP $PERFDIR/perf.data
-
-	i=1
-	while [ $i -le $num_stream ]; do
-		j=1
-		while [ $j -le 22 ]; do
-			PERFDIR=$OUTPUT_DIR/results/$i/perf/$j
-			PERFPREFIX=q$j
-			perf report -i $PERFDIR/$PERFPREFIX-perf.data -n \
-					> $PERFDIR/$PERFPREFIX-perf-report.txt
-			$GZIP $PERFDIR/$PERFPREFIX-perf-report.txt
-			perf annotate -l -P -i $PERFDIR/$PERFPREFIX-perf.data \
-					> $PERFDIR/$PERFPREFIX-perf-annotate.txt
-			$GZIP $PERFDIR/$PERFPREFIX-perf-annotate.txt
-			perf script -L -i $PERFDIR/$PERFPREFIX-perf.data \
-					> $PERFDIR/$PERFPREFIX-perf-trace.txt
-			$GZIP $PERFDIR/$PERFPREFIX-perf-trace.txt
-			$GZIP $PERFDIR/$PERFPREFIX-perf.data
-			j=$(( $j + 1 ))
-		done
-		i=$(( $i + 1 ))
-	done > $OUTPUT_DIR/perf/perf-output.txt 2>&1
-	wait
+if [ "${MPP}" -eq 0 ] && [ "${PROFILE}" -eq 1 ]; then
+	echo "Generating profiling reports for throughput test..."
+	ts-profile -o "${PERFDIR}" -p
 fi
