Convert plot-results to use gnuplot
Use gnuplot because it has fewer package dependencies than R on some
Linux distributions, and its license compatibility is better for
potential AppImages of the test kit.

diff --git a/scripts/dbt3-plot-results.in b/scripts/dbt3-plot-results.in
--- a/scripts/dbt3-plot-results.in
+++ b/scripts/dbt3-plot-results.in
@@ -7,35 +7,16 @@
 # Copyright (C) 2014      Mark Wong
 #               2014      2ndQuadrant, Ltd.
 
-POWER_TEST=0
-THROUGHPUT_TEST=0
-
 usage()
 {
-	echo "usage: `basename $0` [-23hz] [-i q_time.csv] [-o directory]"
-	echo " 2 - power test data"
-	echo " 3 - throughput test data"
+	echo "usage: $(basename "${0}") -i q_time.csv -o directory"
 	echo " i - query time csv data file"
 	echo " o - output directory to save bar charts"
-	echo " z - no refresh stream data"
 }
 
-ABDIR="v"
-BPDIR="T"
 OUTDIR="."
-POWER_TEST=0
-THROUGHPUT_TEST=0
-while getopts "23f:hi:o:Vz" opt; do
+while getopts "hi:o:" opt; do
 	case $opt in
-	2)
-		POWER_TEST=1
-		;;
-	3)
-		THROUGHPUT_TEST=1
-		;;
-	f)
-		SCALE_FACTOR=${OPTARG}
-		;;
 	h)
 		usage
 		exit 0
@@ -46,104 +27,109 @@ while getopts "23f:hi:o:Vz" opt; do
 	o)
 		OUTDIR=${OPTARG}
 		;;
-	V)
-		ABDIR="h"
-		BPDIR="F"
-		;;
-	z)
-		NO_REFRESH_FLAG="-z"
-		;;
 	\?)
 		exit 1
 		;;
 	esac
 done
 
-R --slave --no-save << __EOF__
-df <- read.csv("${INFILE}", header=T)
+if [ ! -f "${INFILE}" ]; then
+	echo "ERROR: '${INFILE}' not found"
+	exit 1
+fi
 
-count <- 0
-labels <- NULL
-cnames <- NULL
-power <- NULL
-thruput <- NULL
+PLOTLINE=""
 
-df\$q <- NA
+PCOUNT="$(grep -c "^PERF\.POWER" "${INFILE}")"
+TCOUNT="$(grep -c "^PERF\.THRUPUT" "${INFILE}")"
 
-df_plot <- df[0, ]
+if [ "${PCOUNT}" -eq 0 ] && [ "${TCOUNT}" -eq 0 ]; then
+	echo "ERROR: no data to plot from '${INFILE}'"
+	exit 1
+fi
 
-for (i in 1:22) {
-  cnames <- c(cnames, paste("Q", i, sep=""))
-}
-cnames <- c(cnames, "RF1")
-cnames <- c(cnames, "RF2")
+PDATAFILE=$(mktemp)
+TDATAFILE=$(mktemp)
 
-if (${POWER_TEST} == 1) {
-  df_power <- df[0, ]
-  count <- count + 1
-  labels <- c(labels, "Power")
+if [ "${PCOUNT}" -ne 0 ]; then
+	# Natural sort seems to fail, so grep one at a time from the Power results.
+	for Q in $(seq 1 22); do
+		VALUE=$(grep "^PERF\.POWER\.Q${Q}," "${INFILE}" | cut -d "," -f 5 \
+				| xargs | tr ' ' + | bc -l)
+		echo "Q${Q} ${VALUE}" >> "${PDATAFILE}"
+	done
+	for RF in $(seq 1 2); do
+		VALUE=$(grep "^PERF\.POWER\.RF${RF}," "${INFILE}" | \
+				cut -d "," -f 5 | xargs | tr ' ' + | bc -l)
+		echo "RF${RF} ${VALUE}" >> "${PDATAFILE}"
+	done
+else
+	# Create a empty set of data for the Power test so if there is Throughput
+	# test to plot, then the colors will be consistent.
+	cat <<- EOF > "${PDATAFILE}"
+		Q1 0
+		Q2 0
+		Q3 0
+		Q4 0
+		Q5 0
+		Q6 0
+		Q7 0
+		Q8 0
+		Q9 0
+		Q10 0
+		Q11 0
+		Q12 0
+		Q13 0
+		Q14 0
+		Q15 0
+		Q16 0
+		Q17 0
+		Q18 0
+		Q19 0
+		Q20 0
+		Q21 0
+		Q22 0
+		RF1 0
+		RF2 0
+	EOF
+	PLOTLINE="'${PDATAFILE}' using 2:xtic(1) notitle,"
+fi
 
-  for (i in 1:22) {
-    str <- paste("PERF.POWER.Q", i, sep="")
-    df[df\$task_name == str, ]\$q = i
-    df_power <- rbind(df_power, df[df\$task_name == str, ])
-  }
-  df[df\$task_name == "PERF.POWER.RF1", ]\$q = 23
-  df[df\$task_name == "PERF.POWER.RF2", ]\$q = 24
-  df_power <- rbind(df_power, df[df\$task_name == "PERF.POWER.RF1", ])
-  df_power <- rbind(df_power, df[df\$task_name == "PERF.POWER.RF2", ])
+if [ "${TCOUNT}" -ne 0 ]; then
+	STREAMS=$(grep -c "^PERF\.THRUPUT\.QS.*\.Q1," "${INFILE}")
+	for Q in $(seq 1 22); do
+		SUM=$(grep "^PERF\.THRUPUT\.QS.*\.Q${Q}," "${INFILE}" | cut -d "," -f 5 \
+				| xargs | tr ' ' + | bc -l)
+		AVG=$(echo "${SUM} / ${STREAMS}" | bc -l)
+		echo "Q${Q} ${AVG}" >> "${TDATAFILE}"
+	done
+	for RF in $(seq 1 2); do
+		SUM=$(grep "^PERF\.THRUPUT\.RFST.*\.RF${RF}," "${INFILE}" | \
+				cut -d "," -f 5 | xargs | tr ' ' + | bc -l)
+		AVG=$(echo "${SUM} / ${STREAMS}" | bc -l)
+		echo "RF${RF} ${AVG}" >> "${TDATAFILE}"
+	done
+fi
 
-  df_power <- df_power[with(df_power, order(q)), ]
+if [ "${PCOUNT}" -ne 0 ]; then
+	PLOTLINE="'${PDATAFILE}' using 2:xtic(1) title 'Power'"
+fi
+if [ "${TCOUNT}" -ne 0 ]; then
+	if [ "${PCOUNT}" -ne 0 ]; then
+		PLOTLINE="${PLOTLINE},"
+	fi
+	PLOTLINE="${PLOTLINE} '${TDATAFILE}' using 2:xtic(1) title 'Throughput'"
+fi
 
-  df_plot <- rbind(df_plot, df_power)
+gnuplot << EOF
+set terminal pngcairo size 1600,1000
+set title "Query Execution Time"
+set grid
+set output "${OUTDIR}/q_time.png"
+set ylabel "Seconds"
+set style data histogram
+set style fill solid
+plot ${PLOTLINE}
+EOF
 
-  power <- 3600 * $SCALE_FACTOR /
-           prod(df_power\$seconds) ^ (1 / length(df_power\$seconds))
-}
-
-if (${THROUGHPUT_TEST} == 1) {
-  df_thruput <- df[grep("*.THRUPUT.QS.*.ALL", df\$task_name), ]
-  runs <- nrow(df_thruput)
-  labels <- c(labels, "Throughput")
-  count <- count + 1
-
-  df_thruput <- df[0, ]
-  for (i in 1:22) {
-    str <- paste("*.THRUPUT.QS.*.Q", i, "\$", sep="")
-    sub <- df[grep(str, df\$task_name), ]
-    newrow <- data.frame(task_name=paste("THRUPUT.Q", i, sep=""), s_time=0,
-                         e_time=0, diff_time=0, seconds=mean(sub\$seconds), q=i)
-    df_thruput <- rbind(df_thruput, newrow)
-  }
-  for (i in 1:2) {
-    str <- paste("*.THRUPUT.*.RF", i, sep="")
-    sub <- df[grep(str, df\$task_name), ]
-    newrow <- data.frame(task_name=paste("THRUPUT.RF", i, sep=""), s_time=0,
-                         e_time=0, diff_time=0, seconds=mean(sub\$seconds),
-                         q=(i + 22))
-    df_thruput <- rbind(df_thruput, newrow)
-  }
-  df_plot <- rbind(df_plot, df_thruput)
-  thruput <- sum(df_thruput\$seconds) / (runs * 22)
-}
-
-data <- matrix(df_plot\$seconds, ncol=24, byrow=T)
-colnames(data) <- cnames
-rownames(data) <- labels
-
-colors <- cm.colors(count)
-df_plot <- df_plot[with(df_plot, order(q, task_name)), ]
-bitmap("${OUTDIR}/q_time.png", type="png16m", units="px",
-       width=1437, height=888, res=150, taa=4, gaa=4)
-barplot(data, col=colors, beside=T, horiz=$BPDIR, las=1,
-        main="Query Execution Time", xlab="Seconds")
-if (is.null(power) == F) {
-  abline($ABDIR=power)
-}
-if (is.null(thruput) == F) {
-  abline($ABDIR=thruput)
-}
-legend("topright", legend=labels, fil=colors, bty="n")
-grid(col="gray")
-invisible(dev.off())
-__EOF__
+rm "${PDATAFILE}" "${TDATAFILE}"
